function model = LossMeasure(model)

model.LossTrain(model.IdxEpoch) = (-1/model.NumTrain)*((model.YabtTrain*log(model.PabtTrain'))+((1-model.YabtTrain)*log((1-model.PabtTrain')))) ...
                                + (-1/model.NumTrain)*((model.YgfaTrain*log(model.PgfaTrain'))+((1-model.YgfaTrain)*log((1-model.PgfaTrain')))) ...
                                + (-1/model.NumTrain)*((model.YnflTrain*log(model.PnflTrain'))+((1-model.YnflTrain)*log((1-model.PnflTrain')))) ...
                                + (-1/model.NumTrain)*((model.YtauTrain*log(model.PtauTrain'))+((1-model.YtauTrain)*log((1-model.PtauTrain'))));

model.LossValid(model.IdxEpoch) = (-1/model.NumValid)*((model.YabtValid*log(model.PabtValid'))+((1-model.YabtValid)*log((1-model.PabtValid')))) ...
                                + (-1/model.NumValid)*((model.YgfaValid*log(model.PgfaValid'))+((1-model.YgfaValid)*log((1-model.PgfaValid')))) ...
                                + (-1/model.NumValid)*((model.YnflValid*log(model.PnflValid'))+((1-model.YnflValid)*log((1-model.PnflValid')))) ...
                                + (-1/model.NumValid)*((model.YtauValid*log(model.PtauValid'))+((1-model.YtauValid)*log((1-model.PtauValid'))));